name: Update sitemap
on:
  schedule:
    - cron: "0 0 * * *"   # täglich 00:00 UTC
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install lxml

      - name: Generate sitemap_auto.xml
        run: |
          python generate_sitemap.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap_auto.xml sitemap_index.xml || true
          git commit -m "auto: refresh sitemap" || echo "No changes"
          git push
