name: Update ALL sitemaps
on:
  schedule:
    - cron: "0 0 * * *"      # täglich 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: sitemap
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SITEMAP_BASE: https://sitemap.kellereiladen.de

      # Aggressives Finetuning (von generate_sitemap_products_headless.js gelesen)
      KL_RETAIN_DAYS: "35"           # Produkte 35 Tage im Cache halten
      KL_REFRESH_AFTER_DAYS: "7"     # ab Tag 7 refreshtesten (HEAD/GET)
      KL_RESPECT_ROBOTS: "0"         # "1" = robots.txt strikt, "0" = ignorieren
      KL_REFRESH_CONCURRENCY: "10"   # parallele HEAD/GET Checks
      KL_REFRESH_TIMEOUT_MS: "15000" # Timeout pro Check (ms)

    steps:
      - uses: actions/checkout@v4

      # 1) AUTO-SITEMAP (Python)
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install lxml
      - name: Build sitemap_auto.xml
        run: |
          python generate_sitemap.py

      # 2) PRODUKT-SITEMAPS (Headless, Stealth)
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Node deps
        run: npm install --no-audit --no-fund
      - name: Build product sitemaps
        run: npm run build:sitemap

      # 3) Commit
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap*.xml products_seen.json || true
          git commit -m "auto: refresh all sitemaps" || echo "No changes"
          git push

